services:
  quotes-pgdb:
    image: postgres:17.5-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: quotes
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - quotes_pgdb_data:/var/lib/postgresql/data

volumes:
  quotes_pgdb_data:
