name: Deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies and build
        working-directory: ./client
        run: |
          npm install
          npm run build

      - name: Clean contents of target folder on VPS
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            rm -rf ~/quotes/client/dist/* ~/quotes/client/dist/.* 2>/dev/null || true

      - name: Upload built files to VPS
        uses: appleboy/scp-action@v0.1.6
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          source: "./client/dist/*"
          target: "~/quotes/client/dist/"
          strip_components: 2
