name: Deploy
on:
  push:
    branches: [main]

permissions:
  packages: write

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "22.17.x"
      # todo: use turborepo for deps and lint
      - name: Install dependencies
        run: cd client && npm ci
      - name: Lint
        run: cd client && npm run lint

  build-and-push-image:
    runs-on: ubuntu-latest
    needs:
      - lint
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: https://ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push client image
        uses: docker/build-push-action@v6
        with:
          context: ./client
          push: true
          tags: |
            ghcr.io/zhadko-bazilevych/quotes/client:latest
            ghcr.io/zhadko-bazilevych/quotes/client:${{ github.sha }}

      - name: Build and push caddy image
        uses: docker/build-push-action@v6
        with:
          context: ./caddy
          push: true
          tags: |
            ghcr.io/zhadko-bazilevych/quotes/caddy:latest
            ghcr.io/zhadko-bazilevych/quotes/caddy:${{ github.sha }}

  deploy:
    runs-on: ubuntu-latest
    environment: production
    needs:
      - build-and-push-image
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create env file
        run: |
          echo "GIT_COMMIT_HASH=${{ github.sha }}" >> ./envfile

      - name: Docker Stack Deploy
        uses: cssnr/stack-deploy-action@v1
        with:
          name: quotes
          file: docker-stack.yaml
          host: ${{ secrets.VPS_HOST }}
          user: ${{ secrets.VPS_USER }}
          ssh_key: ${{ secrets.VPS_SSH_KEY }}
          env_file: ./envfile
